### ISSUE TITLE
Petit bug

### ISSUE THREAD

**Issue by javaskater** [mikaelmeulle/custom_formation#1]
## l'activation du module:

```bash
jpmena@jpmena-HP-ProDesk-600-G2-MT ~/REFBOFIP/formation3/web $ php ../vendor/drush/drush/drush.php en -y custom_formation
The following extensions will be enabled: custom_formation
Do you really want to continue? (y/n): y
ReflectionException: Class Drupal\custom_formation\EventSubscriber\MyCustomEventSubScriber does not exist in                                                                        [error]
/home/jpmena/REFBOFIP/formation3/web/core/lib/Drupal/Core/DependencyInjection/Compiler/RegisterEventSubscribersPass.php:30
```

en fait il y  avait juste un prblème de chemin dans l'annotation @package de la classe __MyCustomEventSubScriber__ j'ai corrigé sur _custom_formation/src/EventSubscriber/MyCustomEventSubscriber.php_ les chemins liés aux annotations @file et @package ce qui donne pous cette classe java:

```java
<?php
/**
 * @file
 * Contains \Drupal\custom_formation\EventSubscriber\MyCustomEventSubScriber.
 */
namespace Drupal\custom_formation\EventSubscriber;
use Drupal\Core\Config\ConfigCrudEvent;
use Drupal\Core\Config\ConfigEvents;
use Drupal\custom_formation\CustomEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
/**
 * Class MyCustomEventSubScriber.
 *
 * @package Drupal\custom_formation\EventSubscriber
 */
class MyCustomEventSubScriber implements EventSubscriberInterface {
  /**
   * {@inheritdoc}
   */
  public static function getSubscribedEvents() {
    $events[ConfigEvents::SAVE][] = array('onSavingConfig', 800);
    $events[CustomEvent::SUBMIT][] = array('doSomeAction', 800);
    return $events;
  }
  /**
   * Subscriber Callback for the event.
   * @param CustomEvent $event
   */
  public function doSomeAction(CustomEvent $event) {
    \Drupal::logger("custom_formation")->info("evenement recu: ".$event->getCustomProperty());
  }
  /**
   * Subscriber Callback for the event.
   * @param ConfigCrudEvent $event
   */
  public function onSavingConfig(ConfigCrudEvent $event) {
    drupal_set_message("You have saved a configuration of " . $event->getConfig()->getName());
  }
}
```

**Comment by mikaelmeulle** [comment]
bonjour,
merci ! c'est commité.
https://github.com/mikaelmeulle/custom_formation/commit/f1d9d34c86ee3fc85a377e84948c1b97722f3f0a

**Comment by javaskater** [comment]
## en fait le problème était entre :

- le nome de la classe: __MyCustomEventSubscriber__ (Subscriber a une seule majuscule)
- le nom du fichier: _custom_formation/src/EventSubscriber/MyCustomEventSubScriber.php_  (je vois qu'il a été commité récemment avec Subscriber a une seule majuscule!

# Attention au fichier services.yml !!!

- il pointe toujours vers MyCustomEventSubScriber.php (avec  2 majuscules pour SubScriber)
  - je l'ai corrigé localement pour :

```yaml
services:
  custom_formation.route_subscriber:
    class: Drupal\custom_formation\Routing\CustomRouteSubscriber
    tags:
      - { name: event_subscriber }
  custom_formation.event_subscriber_example:
    class: Drupal\custom_formation\EventSubscriber\MyCustomEventSubscriber
    tags:
      - { name: 'event_subscriber' }
  
  custom_formation.mon_service:
    class: Drupal\custom_formation\MonService
    arguments: ['@current_user']
```

## après ces modif, 

### les commandes drush passent à nouveau
